function [tbc, trc] = getTrapBoundaryCells(Gt,trap,trap_i)
%GETTRAPBOUNDARYCELLS Get indices of cells that form the boundary of a trap. 
%
%   PARAMETERS:
%
%       Gt      -  top surface grid (called by MRST:co2lab:topSurfaceGrid(Gt);
%       trap    -  trap structure generated by MRST:co2lab:trapAnalysis(Gt)
%       trap_i  -  index of trap from which the boundary is intended.
%
%   RETURNS:
%
%       tbc     - cell indices of the top grid that form the trap's boundary.
%       trc     - cell indices of the trap region.
%                 
%
%   REMARK: the trap boundary is the outermost "belt" (closed hull) of
%   cells that belong to the trap region.

% get trap_region
trc = find(trap.trap_regions == trap_i);

% reduced grid
Gts = extractSubgrid(Gt,trc);

% get boundary cells
bndyfac = any(Gts.faces.neighbors == 0, 2);
bndycells = accumarray(sum(Gts.faces.neighbors(bndyfac,:), 2), 1) > 0;

% returns global indices
tbc = trc(bndycells);

end
