%% CASE: LaMEP/LCPetro - heterogeneous 

mrstVerbose off  % turn on verbose

% TODO This model has the keyword 'EQUALSI' for KY and KZ
% Hence, the code does not stores PROPS.KY and PROPS.KZ. 
% We have to fill the blanks manually here. The processing 
% of this should be implemented into WELLPS. 
%
% .mat G and PROPS generated manually because readCMGDataset 
% still does not handle files from STARS
%
% Reading of properties generated by geostatistical module 
% is required.

%% Loading pre-stored grid 

d = DirManager(); 

load(fullfile(d.getBenchMarksDir,'lamep-lcpetro','mrst','LL-H-1-G.mat'));
load(fullfile(d.getBenchMarksDir,'lamep-lcpetro','mrst','LL-H-1-PROPS.mat'));


% ploting
%plotCellData(G,PROPS.PHI);

%% Clustering
S = getStats(d,P,{'DRTN_LN','DRTH_LN','DRTG_LN'},'n');

% number of significant cells
nofsc = 30;

% (harmonic, nofsc = 30, DRT 1-12) => {339,2} clusters for DRT = {11,12}
% (normalized, nofsc = 20,30, DRT 7-11) => 0 clusters for all
drtN = S{1}(2:end,1);
drtStN = findDRTConnections(d,drtN, P, 'normalized','ln',nofsc,'y', 1);
drtH = S{2}(3:end,1);
drtStH = findDRTConnections(d,drtH, P, 'harmonic','ln',nofsc,'y', 1);
drtG = S{3}(1:end,1);
drtStG = findDRTConnections(d,drtG, P, 'geometric','ln',nofsc,'y', 1);


%% Metrics analyzer
opt.nofsc = nofsc;    
opt.seps = 0.05;
opt.R2min = 0.9;

% compute
[mH,lH] = computeDRTGraphMetrics(opt,drtStH);



